# Generated by Django 4.2.2 on 2023-08-23 04:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakao_id',
            field=models.PositiveIntegerField(null=True, verbose_name='카카오 연동 계정 pk'),
        ),
        migrations.AddField(
            model_name='user',
            name='like_restaurant',
            field=models.ManyToManyField(blank=True, default=[], related_name='like_users', to='restaurant.restaurant', verbose_name='찜한 식당 목록'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^010-?[1-9]\\d{3}-?\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='users', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'pdf', 'svg'])], verbose_name='프로필 이미지'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_nickname',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
