# Generated by Django 4.2.2 on 2023-08-05 09:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=10, verbose_name='회사 이름')),
                ('link', models.URLField(blank=True, verbose_name='광고 링크')),
                ('image', models.FileField(blank=True, upload_to='ads', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'pdf', 'svg'])], verbose_name='광고 이미지')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='상권 이름')),
                ('image', models.FileField(blank=True, upload_to='groups', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'pdf', 'svg'])], verbose_name='상권 로고')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='상권 소개')),
            ],
        ),
    ]
