# Generated by Django 4.2.2 on 2023-08-05 09:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='식당 이름')),
                ('image', models.FileField(blank=True, upload_to='restaurants', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'pdf', 'svg'])], verbose_name='식당 이미지')),
                ('deposit', models.PositiveIntegerField(default=0, verbose_name='보증금')),
                ('open_hour', models.TimeField(verbose_name='오픈 시간')),
                ('close_hour', models.TimeField(verbose_name='마감 시간')),
                ('available', models.BooleanField(default=False, verbose_name='예약 가능 여부')),
                ('empty_seat', models.PositiveIntegerField(default=0, verbose_name='현재 빈 좌석수')),
                ('total_seat', models.PositiveIntegerField(default=0, verbose_name='총 좌석수')),
                ('is_ad', models.BooleanField(default=False, verbose_name='광고 신청 여부')),
                ('tel', models.CharField(max_length=13, unique=True, verbose_name='대표 번호')),
                ('description', models.TextField(blank=True, max_length=20, verbose_name='식당 설명')),
                ('location', models.TextField(verbose_name='식당 주소')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='상권 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='리뷰 작성 일시')),
                ('content', models.TextField(max_length=200, verbose_name='리뷰 내용')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='별점')),
                ('image', models.FileField(blank=True, upload_to='reviews', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'pdf', 'svg'])], verbose_name='리뷰사진')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant', verbose_name='식당 이름')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_time', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='최대 이용 시간')),
                ('description', models.TextField(blank=True, verbose_name='추가 유의 사항')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant', verbose_name='식당 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='음식 이름')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='대표 음식 여부')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='음식 가격')),
                ('image', models.FileField(blank=True, upload_to='Restaurant/menu', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'pdf', 'svg'])], verbose_name='음식 사진')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='음식 소개')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant', verbose_name='식당 이름')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalseats', models.PositiveIntegerField(default=1, verbose_name='총 자리 수')),
                ('floor', models.PositiveSmallIntegerField(default=1, verbose_name='층 수')),
                ('whetherdeposit', models.BooleanField(default=False, verbose_name='보증금 여부')),
                ('parking', models.BooleanField(default=False, verbose_name='주차 가능 여부')),
                ('crowded', models.CharField(choices=[('CROWDED', 'Crowded'), ('NEUTRAL', 'Neutral'), ('QUIET', 'Quiet')], default='QUIET', max_length=10, verbose_name='분위기')),
                ('tvscreen', models.BooleanField(default=False, verbose_name='스크린 여부')),
                ('minimum_pay', models.TextField(blank=True, max_length=100, verbose_name='최소 주문 금액')),
                ('limited_time', models.PositiveIntegerField(default=1, verbose_name='대관 제한시간')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant', verbose_name='식당 이름')),
            ],
        ),
    ]
