# Generated by Django 4.2.2 on 2023-08-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_feature_minimum_pay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='minimum_pay',
        ),
        migrations.AddField(
            model_name='feature',
            name='minimum_order',
            field=models.TextField(default=False, max_length=200, verbose_name='최소 주문 제한'),
        ),
    ]
