# Generated by Django 4.2.2 on 2023-08-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_feature_minimum_pay_feature_minimum_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='minimum_order',
            field=models.TextField(default=False, max_length=200, verbose_name='최소 주문 기준'),
        ),
    ]
