# Generated by Django 4.2.2 on 2023-11-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_rename_created_review_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='식당 설명'),
        ),
    ]
